name: CD - Deploy with Terraform

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: true
      repo_url:
        description: 'ECR repo URL (e.g. 123456789012.dkr.ecr.us-east-1.amazonaws.com/strapi-app)'
        required: true

  repository_dispatch:
    types: [trigger-terraform]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Init Terraform
        working-directory: terraform
        run: terraform init

      - name: Plan Terraform
        working-directory: terraform
        run: |
          IMAGE_TAG="${{ github.event.inputs.image_tag || github.event.client_payload.image_tag }}"
          REPO_URL="${{ github.event.inputs.repo_url || github.event.client_payload.repo_url }}"

          terraform plan \
            -var="image_tag=$IMAGE_TAG" \
            -var="repo_url=$REPO_URL" \
            -out=tfplan

      - name: Apply Terraform
        working-directory: terraform
        run: terraform apply -auto-approve tfplan

      - name: Show EC2 Public IP
        working-directory: terraform
        run: terraform output strapi_public_ip

